imports:
    - { resource: "../parameters.yml" }

framework:
    secret: %framework.secret%
    router:
        resource: "%kernel.config_dir%/routing.yml"
        strict_requirements: "%kernel.debug%"
